version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: energy-postgres
    environment:
      POSTGRES_DB: energy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  api:
    container_name: energy-api
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/energy
    depends_on:
      - postgres

